"""reddit author add text removed

Revision ID: 5be8c6151379
Revises: 3edf6dacf69f
Create Date: 2025-07-15 16:16:04.930010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be8c6151379'
down_revision = '3edf6dacf69f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reddit_agent_execution_mapper_post_id_fkey', 'reddit_agent_execution_mapper', type_='foreignkey')
    op.create_foreign_key(None, 'reddit_agent_execution_mapper', 'reddit_posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.add_column('reddit_posts', sa.Column('post_author', sa.String(), nullable=True))
    op.drop_column('reddit_posts', 'text')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_posts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('reddit_posts', 'post_author')
    op.drop_constraint(None, 'reddit_agent_execution_mapper', type_='foreignkey')
    op.create_foreign_key('reddit_agent_execution_mapper_post_id_fkey', 'reddit_agent_execution_mapper', 'reddit_posts', ['post_id'], ['post_id'])
    # ### end Alembic commands ###